steps:
  - label: ":golang:"
    agents:
      queue: "*"
      docker: "*"
    command: "cd /go && ls -al"
    plugins:
      - docker-compose#v3.0.0:
          run: app
          config: docker/buildkite/docker-compose.yml
