steps:
  - label: ":golang:"
    agents:
      queue: workers
    command: "/myfolder/scripts/test.sh"
    plugins:
      - docker-compose#v3.0.0:
          run: app
          config: docker/buildkite/docker-compose.yml
