steps:
  - label: ":golang:"
    agents:
      queue: workers
    command: "ls -al"
    plugins:
      - docker-compose#v3.0.0:
          run: app
          config: docker/buildkite/docker-compose.yml
